packages:
  - apps/*
  - packages/*

allowBuilds:
  core-js: true
  esbuild: true
  protobufjs: true
  react-native-enriched-markdown: true
  sharp: true
  unrs-resolver: true

onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@tailwindcss/oxide'
  - better-sqlite3
  - core-js
  - esbuild
  - react-native-enriched-markdown
  - sharp
