// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/airside-carriers" | "/airside-filings" | "/benchmarks" | "/benchmarks/[id]" | "/chat-plans" | "/chat-plans/[orgId]" | "/chat-support-logs" | "/chat-support-logs/[id]" | "/contact-submissions" | "/contact-submissions/[id]" | "/content-filter" | "/devpass" | "/devpass/[orgId]" | "/discounts" | "/flagged-accounts" | "/global-stats" | "/license-required" | "/limit-hits" | "/login" | "/model-provider-mappings" | "/model-provider-mappings/[providerId]/[modelId]" | "/models" | "/models/[modelId]" | "/organizations" | "/organizations/[orgId]" | "/organizations/[orgId]/discounts" | "/organizations/[orgId]/projects/[projectId]" | "/organizations/[orgId]/projects/[projectId]/model-provider-mappings" | "/organizations/[orgId]/rate-limits" | "/payment-failures" | "/provider-credentials" | "/provider-listing-requests" | "/provider-listing-requests/[id]" | "/providers" | "/providers/[providerId]" | "/providers/[providerId]/incidents" | "/rate-limits" | "/routing-analytics" | "/sdk" | "/settings" | "/unstable-mappings"
type AppRouteHandlerRoutes = "/api/generate-reply" | "/api/health"
type PageRoutes = never
type LayoutRoutes = "/"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/airside-carriers": {}
  "/airside-filings": {}
  "/api/generate-reply": {}
  "/api/health": {}
  "/benchmarks": {}
  "/benchmarks/[id]": { "id": string; }
  "/chat-plans": {}
  "/chat-plans/[orgId]": { "orgId": string; }
  "/chat-support-logs": {}
  "/chat-support-logs/[id]": { "id": string; }
  "/contact-submissions": {}
  "/contact-submissions/[id]": { "id": string; }
  "/content-filter": {}
  "/devpass": {}
  "/devpass/[orgId]": { "orgId": string; }
  "/discounts": {}
  "/flagged-accounts": {}
  "/global-stats": {}
  "/license-required": {}
  "/limit-hits": {}
  "/login": {}
  "/model-provider-mappings": {}
  "/model-provider-mappings/[providerId]/[modelId]": { "providerId": string; "modelId": string; }
  "/models": {}
  "/models/[modelId]": { "modelId": string; }
  "/organizations": {}
  "/organizations/[orgId]": { "orgId": string; }
  "/organizations/[orgId]/discounts": { "orgId": string; }
  "/organizations/[orgId]/projects/[projectId]": { "orgId": string; "projectId": string; }
  "/organizations/[orgId]/projects/[projectId]/model-provider-mappings": { "orgId": string; "projectId": string; }
  "/organizations/[orgId]/rate-limits": { "orgId": string; }
  "/payment-failures": {}
  "/provider-credentials": {}
  "/provider-listing-requests": {}
  "/provider-listing-requests/[id]": { "id": string; }
  "/providers": {}
  "/providers/[providerId]": { "providerId": string; }
  "/providers/[providerId]/incidents": { "providerId": string; }
  "/rate-limits": {}
  "/routing-analytics": {}
  "/sdk": {}
  "/settings": {}
  "/unstable-mappings": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
