// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../../src/app/airside-carriers/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/airside-carriers">> = Specific
  const handler = {} as typeof import("../../../src/app/airside-carriers/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/airside-filings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/airside-filings">> = Specific
  const handler = {} as typeof import("../../../src/app/airside-filings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/benchmarks/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/benchmarks/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/benchmarks/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/benchmarks/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/benchmarks">> = Specific
  const handler = {} as typeof import("../../../src/app/benchmarks/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/chat-plans/[orgId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/chat-plans/[orgId]">> = Specific
  const handler = {} as typeof import("../../../src/app/chat-plans/[orgId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/chat-plans/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/chat-plans">> = Specific
  const handler = {} as typeof import("../../../src/app/chat-plans/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/chat-support-logs/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/chat-support-logs/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/chat-support-logs/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/chat-support-logs/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/chat-support-logs">> = Specific
  const handler = {} as typeof import("../../../src/app/chat-support-logs/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/contact-submissions/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/contact-submissions/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/contact-submissions/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/contact-submissions/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/contact-submissions">> = Specific
  const handler = {} as typeof import("../../../src/app/contact-submissions/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/content-filter/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/content-filter">> = Specific
  const handler = {} as typeof import("../../../src/app/content-filter/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/devpass/[orgId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/devpass/[orgId]">> = Specific
  const handler = {} as typeof import("../../../src/app/devpass/[orgId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/devpass/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/devpass">> = Specific
  const handler = {} as typeof import("../../../src/app/devpass/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/discounts/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/discounts">> = Specific
  const handler = {} as typeof import("../../../src/app/discounts/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/flagged-accounts/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/flagged-accounts">> = Specific
  const handler = {} as typeof import("../../../src/app/flagged-accounts/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/global-stats/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/global-stats">> = Specific
  const handler = {} as typeof import("../../../src/app/global-stats/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/license-required/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/license-required">> = Specific
  const handler = {} as typeof import("../../../src/app/license-required/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/limit-hits/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/limit-hits">> = Specific
  const handler = {} as typeof import("../../../src/app/limit-hits/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login">> = Specific
  const handler = {} as typeof import("../../../src/app/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/model-provider-mappings/[providerId]/[modelId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/model-provider-mappings/[providerId]/[modelId]">> = Specific
  const handler = {} as typeof import("../../../src/app/model-provider-mappings/[providerId]/[modelId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/model-provider-mappings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/model-provider-mappings">> = Specific
  const handler = {} as typeof import("../../../src/app/model-provider-mappings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/models/[modelId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/models/[modelId]">> = Specific
  const handler = {} as typeof import("../../../src/app/models/[modelId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/models/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/models">> = Specific
  const handler = {} as typeof import("../../../src/app/models/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/organizations/[orgId]/discounts/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/organizations/[orgId]/discounts">> = Specific
  const handler = {} as typeof import("../../../src/app/organizations/[orgId]/discounts/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/organizations/[orgId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/organizations/[orgId]">> = Specific
  const handler = {} as typeof import("../../../src/app/organizations/[orgId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/organizations/[orgId]/projects/[projectId]/model-provider-mappings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/organizations/[orgId]/projects/[projectId]/model-provider-mappings">> = Specific
  const handler = {} as typeof import("../../../src/app/organizations/[orgId]/projects/[projectId]/model-provider-mappings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/organizations/[orgId]/projects/[projectId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/organizations/[orgId]/projects/[projectId]">> = Specific
  const handler = {} as typeof import("../../../src/app/organizations/[orgId]/projects/[projectId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/organizations/[orgId]/rate-limits/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/organizations/[orgId]/rate-limits">> = Specific
  const handler = {} as typeof import("../../../src/app/organizations/[orgId]/rate-limits/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/organizations/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/organizations">> = Specific
  const handler = {} as typeof import("../../../src/app/organizations/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../../src/app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/payment-failures/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/payment-failures">> = Specific
  const handler = {} as typeof import("../../../src/app/payment-failures/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/provider-credentials/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/provider-credentials">> = Specific
  const handler = {} as typeof import("../../../src/app/provider-credentials/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/provider-listing-requests/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/provider-listing-requests/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/provider-listing-requests/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/provider-listing-requests/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/provider-listing-requests">> = Specific
  const handler = {} as typeof import("../../../src/app/provider-listing-requests/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/providers/[providerId]/incidents/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/providers/[providerId]/incidents">> = Specific
  const handler = {} as typeof import("../../../src/app/providers/[providerId]/incidents/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/providers/[providerId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/providers/[providerId]">> = Specific
  const handler = {} as typeof import("../../../src/app/providers/[providerId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/providers/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/providers">> = Specific
  const handler = {} as typeof import("../../../src/app/providers/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/rate-limits/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/rate-limits">> = Specific
  const handler = {} as typeof import("../../../src/app/rate-limits/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/routing-analytics/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/routing-analytics">> = Specific
  const handler = {} as typeof import("../../../src/app/routing-analytics/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/sdk/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/sdk">> = Specific
  const handler = {} as typeof import("../../../src/app/sdk/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/settings">> = Specific
  const handler = {} as typeof import("../../../src/app/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/unstable-mappings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/unstable-mappings">> = Specific
  const handler = {} as typeof import("../../../src/app/unstable-mappings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/generate-reply/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/generate-reply">> = Specific
  const handler = {} as typeof import("../../../src/app/api/generate-reply/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/health/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/health">> = Specific
  const handler = {} as typeof import("../../../src/app/api/health/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
