import type { ModelDefinition } from "@/models.js";

export const vicharModels = [
	{
		id: "vichar-failover-check",
		name: "Vichar Failover Check",
		description:
			"Vichar-internal model used to validate cross-provider failover during the MVP. Bedrock is preferred on price; the openai mapping is exercised by the mock-upstream acceptance test.",
		family: "vichar",
		stability: "experimental",
		releasedAt: new Date("2026-09-26"),
		providers: [
			{
				test: "skip",
				providerId: "aws-bedrock",
				externalId: "meta.llama4-scout-17b-instruct-v1:0",
				inputPrice: "0.17e-6",
				outputPrice: "0.66e-6",
				requestPrice: "0",
				contextSize: 10485760,
				streaming: true,
				vision: false,
				tools: false,
				jsonOutput: false,
				supportedParameters: [
					"temperature",
					"max_tokens",
					"top_p",
					"frequency_penalty",
					"presence_penalty",
				],
			},
			{
				test: "skip",
				providerId: "openrouter",
				externalId: "stealth/space-bunny-alpha",
				inputPrice: "0.15e-6",
				outputPrice: "0.6e-6",
				requestPrice: "0",
				streaming: true,
				vision: false,
				tools: false,
				jsonOutput: false,
				supportedParameters: [
					"temperature",
					"max_tokens",
					"top_p",
					"frequency_penalty",
					"presence_penalty",
				],
			},
			{
				test: "skip",
				providerId: "openai",
				externalId: "gpt-4o-mini",
				inputPrice: "0.14e-6",
				outputPrice: "0.6e-6",
				requestPrice: "0",
				streaming: true,
				vision: false,
				tools: false,
				jsonOutput: false,
				supportedParameters: [
					"temperature",
					"max_tokens",
					"top_p",
					"frequency_penalty",
					"presence_penalty",
				],
			},
		],
	},

	// Stable paid catalogue. Every price, context window and capability below is
	// copied from the live upstream listing (OpenRouter /models), not estimated.
	{
		id: "vichar-deepseek-v3.2",
		name: "DeepSeek V3.2",
		description:
			"DeepSeek V3.2 — low-cost tool-calling model, the budget coding option.",
		family: "vichar",
		releasedAt: new Date("2025-12-01"),
		providers: [
			{
				test: "skip",
				providerId: "openrouter",
				externalId: "deepseek/deepseek-v3.2",
				inputPrice: "0.269e-6",
				cachedInputPrice: "0.1345e-6",
				outputPrice: "0.4e-6",
				requestPrice: "0",
				contextSize: 163840,
				maxOutput: 65536,
				streaming: true,
				vision: false,
				tools: true,
				parallelToolCalls: true,
				reasoning: true,
				jsonOutput: true,
				jsonOutputSchema: true,
				supportedParameters: [
					"temperature",
					"max_tokens",
					"top_p",
					"frequency_penalty",
					"presence_penalty",
					"response_format",
					"tools",
					"tool_choice",
				],
			},
		],
	},
	{
		id: "vichar-qwen3-coder",
		name: "Qwen3 Coder 480B",
		description:
			"Qwen3 Coder 480B A35B — code-specialized MoE model for agentic coding.",
		family: "vichar",
		releasedAt: new Date("2025-07-23"),
		providers: [
			{
				test: "skip",
				providerId: "openrouter",
				externalId: "qwen/qwen3-coder",
				inputPrice: "0.3e-6",
				cachedInputPrice: "0.1e-6",
				outputPrice: "1.0e-6",
				requestPrice: "0",
				contextSize: 262144,
				maxOutput: 65536,
				streaming: true,
				vision: false,
				tools: true,
				parallelToolCalls: true,
				jsonOutput: true,
				jsonOutputSchema: true,
				supportedParameters: [
					"temperature",
					"max_tokens",
					"top_p",
					"frequency_penalty",
					"presence_penalty",
					"response_format",
					"tools",
					"tool_choice",
				],
			},
		],
	},
	{
		id: "vichar-kimi-k2.5",
		name: "Kimi K2.5",
		description:
			"Moonshot Kimi K2.5 — multimodal agentic model, mid-tier coding option.",
		family: "vichar",
		releasedAt: new Date("2026-01-27"),
		providers: [
			{
				test: "skip",
				providerId: "openrouter",
				externalId: "moonshotai/kimi-k2.5",
				inputPrice: "0.45e-6",
				cachedInputPrice: "0.07e-6",
				outputPrice: "2.25e-6",
				requestPrice: "0",
				contextSize: 262144,
				maxOutput: 235929,
				streaming: true,
				vision: true,
				tools: true,
				parallelToolCalls: true,
				reasoning: true,
				jsonOutput: true,
				jsonOutputSchema: true,
				supportedParameters: [
					"temperature",
					"max_tokens",
					"top_p",
					"frequency_penalty",
					"presence_penalty",
					"response_format",
					"tools",
					"tool_choice",
				],
			},
		],
	},
	{
		id: "vichar-gpt-5.2",
		name: "GPT-5.2",
		description: "OpenAI GPT-5.2 — frontier tool-calling model.",
		family: "vichar",
		releasedAt: new Date("2025-12-10"),
		providers: [
			{
				test: "skip",
				providerId: "openrouter",
				externalId: "openai/gpt-5.2",
				inputPrice: "1.75e-6",
				cachedInputPrice: "0.175e-6",
				outputPrice: "14e-6",
				requestPrice: "0",
				contextSize: 400000,
				maxOutput: 128000,
				streaming: true,
				vision: true,
				document: true,
				tools: true,
				parallelToolCalls: true,
				reasoning: true,
				reasoningEfforts: ["minimal", "low", "medium", "high"],
				jsonOutput: true,
				jsonOutputSchema: true,
				supportedParameters: [
					"max_tokens",
					"response_format",
					"reasoning_effort",
					"tools",
					"tool_choice",
				],
			},
		],
	},
	{
		id: "vichar-sonnet-5",
		name: "Claude Sonnet 5",
		description:
			"Anthropic Claude Sonnet 5 — frontier coding model with a 1M context window.",
		family: "vichar",
		releasedAt: new Date("2026-06-30"),
		providers: [
			{
				test: "skip",
				providerId: "openrouter",
				externalId: "anthropic/claude-sonnet-5",
				inputPrice: "2e-6",
				cachedInputPrice: "0.2e-6",
				outputPrice: "10e-6",
				requestPrice: "0",
				contextSize: 1000000,
				maxOutput: 128000,
				streaming: true,
				vision: true,
				document: true,
				tools: true,
				parallelToolCalls: true,
				reasoning: true,
				reasoningEfforts: ["low", "medium", "high"],
				jsonOutput: true,
				jsonOutputSchema: true,
				supportedParameters: [
					"max_tokens",
					"response_format",
					"reasoning_effort",
					"tools",
					"tool_choice",
				],
			},
		],
	},

	// Experimental free tier. Stealth/free upstream models reachable on the
	// deployment's OpenRouter key at zero provider cost, resold at a nominal
	// list price. Free-tier upstreams are rate-limited, unmetered and can change
	// or disappear without notice — never advertise them as stable coding
	// models. `stability: "experimental"` also keeps them out of coding plans
	// (isCodingModel rejects experimental models) and out of default e2e.
	{
		id: "vichar-space-bunny",
		name: "Space Bunny Alpha",
		description:
			"Free experimental model served through OpenRouter's free tier. Default target of auto routing. Not for production workloads.",
		family: "vichar-openrouter",
		stability: "experimental",
		releasedAt: new Date("2026-09-26"),
		providers: [
			{
				test: "skip",
				providerId: "openrouter",
				externalId: "stealth/space-bunny-alpha",
				inputPrice: "0.15e-6",
				outputPrice: "0.6e-6",
				requestPrice: "0",
				contextSize: 1000000,
				maxOutput: 524288,
				streaming: true,
				vision: true,
				tools: true,
				jsonOutput: true,
				reasoning: true,
				supportedParameters: [
					"temperature",
					"max_tokens",
					"top_p",
					"response_format",
					"reasoning_effort",
					"tools",
					"tool_choice",
				],
			},
		],
	},
	{
		id: "vichar-free-router",
		name: "Vichar Free Router",
		description:
			"Routes to any currently available free upstream model; most resilient to per-model rate limits. Experimental — upstream selection is not under our control.",
		family: "vichar-openrouter",
		stability: "experimental",
		releasedAt: new Date("2026-09-26"),
		providers: [
			{
				test: "skip",
				providerId: "openrouter",
				externalId: "openrouter/free",
				inputPrice: "0.15e-6",
				outputPrice: "0.6e-6",
				requestPrice: "0",
				contextSize: 200000,
				streaming: true,
				vision: true,
				tools: true,
				jsonOutput: true,
				jsonOutputSchema: true,
				reasoning: true,
				supportedParameters: [
					"temperature",
					"max_tokens",
					"top_p",
					"frequency_penalty",
					"presence_penalty",
					"response_format",
					"reasoning_effort",
					"tools",
					"tool_choice",
				],
			},
		],
	},
	{
		id: "vichar-nemotron-3-super",
		name: "Nemotron 3 Super 120B",
		description:
			"NVIDIA Nemotron 3 Super (120B, A12B) via OpenRouter's free tier. Experimental.",
		family: "vichar-openrouter",
		stability: "experimental",
		releasedAt: new Date("2026-09-26"),
		providers: [
			{
				test: "skip",
				providerId: "openrouter",
				externalId: "nvidia/nemotron-3-super-120b-a12b:free",
				inputPrice: "0.15e-6",
				outputPrice: "0.6e-6",
				requestPrice: "0",
				contextSize: 262144,
				maxOutput: 235929,
				streaming: true,
				vision: false,
				tools: true,
				jsonOutput: true,
				jsonOutputSchema: true,
				reasoning: true,
				supportedParameters: [
					"temperature",
					"max_tokens",
					"top_p",
					"response_format",
					"reasoning_effort",
					"tools",
					"tool_choice",
				],
			},
		],
	},
	{
		id: "vichar-nemotron-3-ultra",
		name: "Nemotron 3 Ultra 550B",
		description:
			"NVIDIA Nemotron 3 Ultra (550B, A55B) via OpenRouter's free tier. Experimental.",
		family: "vichar-openrouter",
		stability: "experimental",
		releasedAt: new Date("2026-09-26"),
		providers: [
			{
				test: "skip",
				providerId: "openrouter",
				externalId: "nvidia/nemotron-3-ultra-550b-a55b:free",
				inputPrice: "0.15e-6",
				outputPrice: "0.6e-6",
				requestPrice: "0",
				contextSize: 1000000,
				maxOutput: 65536,
				streaming: true,
				vision: false,
				tools: true,
				reasoning: true,
				supportedParameters: [
					"temperature",
					"max_tokens",
					"top_p",
					"reasoning_effort",
					"tools",
					"tool_choice",
				],
			},
		],
	},
	{
		id: "vichar-nemotron-3.5-lightning",
		name: "Nemotron 3.5 Lightning",
		description:
			"NVIDIA Nemotron 3.5 Lightning via OpenRouter's free tier. Experimental.",
		family: "vichar-openrouter",
		stability: "experimental",
		releasedAt: new Date("2026-09-26"),
		providers: [
			{
				test: "skip",
				providerId: "openrouter",
				externalId: "nvidia/nemotron-3.5-lightning:free",
				inputPrice: "0.15e-6",
				outputPrice: "0.6e-6",
				requestPrice: "0",
				contextSize: 1000000,
				maxOutput: 65536,
				streaming: true,
				vision: false,
				tools: true,
				reasoning: true,
				supportedParameters: [
					"temperature",
					"max_tokens",
					"top_p",
					"tools",
					"tool_choice",
				],
			},
		],
	},
	{
		id: "vichar-laguna-s",
		name: "Laguna S 2.1",
		description:
			"Poolside Laguna S 2.1 via OpenRouter's free tier. Experimental.",
		family: "vichar-openrouter",
		stability: "experimental",
		releasedAt: new Date("2026-09-26"),
		providers: [
			{
				test: "skip",
				providerId: "openrouter",
				externalId: "poolside/laguna-s-2.1:free",
				inputPrice: "0.15e-6",
				outputPrice: "0.6e-6",
				requestPrice: "0",
				contextSize: 262144,
				maxOutput: 32768,
				streaming: true,
				vision: false,
				tools: true,
				reasoning: true,
				supportedParameters: [
					"temperature",
					"max_tokens",
					"tools",
					"tool_choice",
				],
			},
		],
	},
	{
		id: "vichar-north-mini-code",
		name: "North Mini Code",
		description:
			"Cohere North Mini Code via OpenRouter's free tier. Experimental.",
		family: "vichar-openrouter",
		stability: "experimental",
		releasedAt: new Date("2026-09-26"),
		providers: [
			{
				test: "skip",
				providerId: "openrouter",
				externalId: "cohere/north-mini-code:free",
				inputPrice: "0.15e-6",
				outputPrice: "0.6e-6",
				requestPrice: "0",
				contextSize: 256000,
				maxOutput: 64000,
				streaming: true,
				vision: false,
				tools: true,
				reasoning: true,
				supportedParameters: [
					"temperature",
					"max_tokens",
					"top_p",
					"frequency_penalty",
					"presence_penalty",
					"tools",
					"tool_choice",
				],
			},
		],
	},
	{
		id: "vichar-lfm-2.5",
		name: "LFM 2.5 2.6B",
		description:
			"Liquid LFM 2.5 (2.6B) via OpenRouter's free tier. Experimental.",
		family: "vichar-openrouter",
		stability: "experimental",
		releasedAt: new Date("2026-09-26"),
		providers: [
			{
				test: "skip",
				providerId: "openrouter",
				externalId: "liquid/lfm-2.5-2.6b:free",
				inputPrice: "0.15e-6",
				outputPrice: "0.6e-6",
				requestPrice: "0",
				contextSize: 65536,
				maxOutput: 8192,
				streaming: true,
				vision: false,
				tools: true,
				jsonOutput: true,
				jsonOutputSchema: true,
				reasoning: true,
				supportedParameters: [
					"temperature",
					"max_tokens",
					"top_p",
					"frequency_penalty",
					"presence_penalty",
					"response_format",
					"tools",
					"tool_choice",
				],
			},
		],
	},
	{
		id: "vichar-dots-3-note",
		name: "Dots 3 Note Preview",
		description:
			"dots.llm 3 Note preview via OpenRouter's free tier. Experimental.",
		family: "vichar-openrouter",
		stability: "experimental",
		releasedAt: new Date("2026-09-26"),
		providers: [
			{
				test: "skip",
				providerId: "openrouter",
				externalId: "dots-studio/dots-3-note-preview:free",
				inputPrice: "0.15e-6",
				outputPrice: "0.6e-6",
				requestPrice: "0",
				contextSize: 512000,
				maxOutput: 460800,
				streaming: true,
				vision: true,
				tools: true,
				jsonOutput: true,
				jsonOutputSchema: true,
				reasoning: true,
				supportedParameters: [
					"temperature",
					"max_tokens",
					"top_p",
					"response_format",
					"tools",
					"tool_choice",
				],
			},
		],
	},
] as const satisfies ModelDefinition[];
