import type { ModelDefinition } from "@/models.js";

export const vicharModels = [
	{
		id: "vichar-failover-check",
		name: "Vichar Failover Check",
		description:
			"Vichar-internal model used to validate cross-provider failover during the MVP. Bedrock is preferred on price; the openai mapping is exercised by the mock-upstream acceptance test.",
		family: "vichar",
		releasedAt: new Date("2026-09-26"),
		providers: [
			{
				test: "skip",
				providerId: "aws-bedrock",
				externalId: "meta.llama4-scout-17b-instruct-v1:0",
				inputPrice: "0.17e-6",
				outputPrice: "0.66e-6",
				requestPrice: "0",
				contextSize: 10485760,
				streaming: true,
				vision: false,
				tools: false,
				jsonOutput: false,
				supportedParameters: [
					"temperature",
					"max_tokens",
					"top_p",
					"frequency_penalty",
					"presence_penalty",
				],
			},
			{
				test: "skip",
				providerId: "openrouter",
				externalId: "stealth/space-bunny-alpha",
				inputPrice: "0.15e-6",
				outputPrice: "0.6e-6",
				requestPrice: "0",
				streaming: true,
				vision: false,
				tools: false,
				jsonOutput: false,
				supportedParameters: [
					"temperature",
					"max_tokens",
					"top_p",
					"frequency_penalty",
					"presence_penalty",
				],
			},
			{
				test: "skip",
				providerId: "openai",
				externalId: "gpt-4o-mini",
				inputPrice: "0.14e-6",
				outputPrice: "0.6e-6",
				requestPrice: "0",
				streaming: true,
				vision: false,
				tools: false,
				jsonOutput: false,
				supportedParameters: [
					"temperature",
					"max_tokens",
					"top_p",
					"frequency_penalty",
					"presence_penalty",
				],
			},
		],
	},
	{
		id: "vichar-space-bunny",
		name: "Space Bunny Alpha",
		description:
			"Stealth model served through OpenRouter's free tier. Default target of auto routing.",
		family: "vichar-openrouter",
		releasedAt: new Date("2026-09-26"),
		providers: [
			{
				test: "skip",
				providerId: "openrouter",
				externalId: "stealth/space-bunny-alpha",
				inputPrice: "0.15e-6",
				outputPrice: "0.6e-6",
				requestPrice: "0",
				contextSize: 1000000,
				streaming: true,
				vision: false,
				tools: false,
				jsonOutput: false,
				reasoning: true,
				supportedParameters: ["temperature", "max_tokens", "top_p"],
			},
		],
	},
	{
		id: "vichar-free-router",
		name: "OpenRouter Free Router",
		description:
			"OpenRouter picks any currently available free model; most resilient to per-model rate limits.",
		family: "vichar-openrouter",
		releasedAt: new Date("2026-09-26"),
		providers: [
			{
				test: "skip",
				providerId: "openrouter",
				externalId: "openrouter/free",
				inputPrice: "0.15e-6",
				outputPrice: "0.6e-6",
				requestPrice: "0",
				contextSize: 200000,
				streaming: true,
				vision: false,
				tools: false,
				jsonOutput: false,
				reasoning: true,
				supportedParameters: ["temperature", "max_tokens", "top_p"],
			},
		],
	},
	{
		id: "vichar-nemotron-3-super",
		name: "Nemotron 3 Super 120B",
		description:
			"NVIDIA Nemotron 3 Super (120B, A12B) via OpenRouter's free tier.",
		family: "vichar-openrouter",
		releasedAt: new Date("2026-09-26"),
		providers: [
			{
				test: "skip",
				providerId: "openrouter",
				externalId: "nvidia/nemotron-3-super-120b-a12b:free",
				inputPrice: "0.15e-6",
				outputPrice: "0.6e-6",
				requestPrice: "0",
				contextSize: 262144,
				streaming: true,
				vision: false,
				tools: false,
				jsonOutput: false,
				reasoning: true,
				supportedParameters: ["temperature", "max_tokens", "top_p"],
			},
		],
	},
	{
		id: "vichar-nemotron-3-ultra",
		name: "Nemotron 3 Ultra 550B",
		description:
			"NVIDIA Nemotron 3 Ultra (550B, A55B) via OpenRouter's free tier.",
		family: "vichar-openrouter",
		releasedAt: new Date("2026-09-26"),
		providers: [
			{
				test: "skip",
				providerId: "openrouter",
				externalId: "nvidia/nemotron-3-ultra-550b-a55b:free",
				inputPrice: "0.15e-6",
				outputPrice: "0.6e-6",
				requestPrice: "0",
				contextSize: 1000000,
				streaming: true,
				vision: false,
				tools: false,
				jsonOutput: false,
				reasoning: true,
				supportedParameters: ["temperature", "max_tokens", "top_p"],
			},
		],
	},
	{
		id: "vichar-nemotron-3.5-lightning",
		name: "Nemotron 3.5 Lightning",
		description: "NVIDIA Nemotron 3.5 Lightning via OpenRouter's free tier.",
		family: "vichar-openrouter",
		releasedAt: new Date("2026-09-26"),
		providers: [
			{
				test: "skip",
				providerId: "openrouter",
				externalId: "nvidia/nemotron-3.5-lightning:free",
				inputPrice: "0.15e-6",
				outputPrice: "0.6e-6",
				requestPrice: "0",
				contextSize: 1000000,
				streaming: true,
				vision: false,
				tools: false,
				jsonOutput: false,
				reasoning: true,
				supportedParameters: ["temperature", "max_tokens", "top_p"],
			},
		],
	},
	{
		id: "vichar-laguna-s",
		name: "Laguna S 2.1",
		description: "Poolside Laguna S 2.1 via OpenRouter's free tier.",
		family: "vichar-openrouter",
		releasedAt: new Date("2026-09-26"),
		providers: [
			{
				test: "skip",
				providerId: "openrouter",
				externalId: "poolside/laguna-s-2.1:free",
				inputPrice: "0.15e-6",
				outputPrice: "0.6e-6",
				requestPrice: "0",
				contextSize: 262144,
				streaming: true,
				vision: false,
				tools: false,
				jsonOutput: false,
				reasoning: true,
				supportedParameters: ["temperature", "max_tokens", "top_p"],
			},
		],
	},
	{
		id: "vichar-north-mini-code",
		name: "North Mini Code",
		description: "Cohere North Mini Code via OpenRouter's free tier.",
		family: "vichar-openrouter",
		releasedAt: new Date("2026-09-26"),
		providers: [
			{
				test: "skip",
				providerId: "openrouter",
				externalId: "cohere/north-mini-code:free",
				inputPrice: "0.15e-6",
				outputPrice: "0.6e-6",
				requestPrice: "0",
				contextSize: 256000,
				streaming: true,
				vision: false,
				tools: false,
				jsonOutput: false,
				reasoning: true,
				supportedParameters: ["temperature", "max_tokens", "top_p"],
			},
		],
	},
	{
		id: "vichar-lfm-2.5",
		name: "LFM 2.5 2.6B",
		description: "Liquid LFM 2.5 (2.6B) via OpenRouter's free tier.",
		family: "vichar-openrouter",
		releasedAt: new Date("2026-09-26"),
		providers: [
			{
				test: "skip",
				providerId: "openrouter",
				externalId: "liquid/lfm-2.5-2.6b:free",
				inputPrice: "0.15e-6",
				outputPrice: "0.6e-6",
				requestPrice: "0",
				contextSize: 65536,
				streaming: true,
				vision: false,
				tools: false,
				jsonOutput: false,
				reasoning: true,
				supportedParameters: ["temperature", "max_tokens", "top_p"],
			},
		],
	},
	{
		id: "vichar-dots-3-note",
		name: "Dots 3 Note Preview",
		description: "dots.llm 3 Note preview via OpenRouter's free tier.",
		family: "vichar-openrouter",
		releasedAt: new Date("2026-09-26"),
		providers: [
			{
				test: "skip",
				providerId: "openrouter",
				externalId: "dots-studio/dots-3-note-preview:free",
				inputPrice: "0.15e-6",
				outputPrice: "0.6e-6",
				requestPrice: "0",
				contextSize: 512000,
				streaming: true,
				vision: false,
				tools: false,
				jsonOutput: false,
				reasoning: true,
				supportedParameters: ["temperature", "max_tokens", "top_p"],
			},
		],
	},
] as const satisfies ModelDefinition[];
