name: ci

on: pull_request

permissions:
  contents: read

jobs:
  autofix:
    runs-on: ubuntu-latest

    if: github.event.pull_request.head.repo.full_name == github.repository && github.event.pull_request.user.login != 'dependabot[bot]'

    steps:
      - name: Autofix
        uses: steebchen/actions/autofix@v0.17.0
        with:
          token: ${{ secrets.GH_TOKEN }}
          format-command: pnpm migrations && pnpm build && pnpm format
