name: prepare

on:
  workflow_call:
    inputs:
      cmd:
        required: true
        type: string

permissions:
  contents: read

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7.0.1
        with:
          persist-credentials: false

      - uses: ./.github/actions/setup

      - name: ${{ inputs.cmd }}
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          set -eux
          ${{ inputs.cmd }}
